application: open-fire
version: placeholder
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1m"


#### ===== Files to Skip
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$


#### ===== Libraries
libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: webob
  version: "latest"
- name: setuptools
  version: "latest"
- name: pycrypto
  version: "latest"


#### ===== Builtin SDK Includes
builtins:
- appstats: on
- deferred: on
- remote_api: on
- admin_redirect: on


#### ===== Incoming Services
inbound_services:
- warmup
#- mail
#- xmpp_message
#- xmpp_presence
#- xmpp_subscribe
#- channel_presence

#### ===== Includes
includes:
- mapreduce/include.yaml

#### ===== Force precompilation
derived_file_type:
- python_precompiled


#### ===== PageSpeed Config
pagespeed:
  domains_to_rewrite:
  - open-fire-staging.appspot.com
  - staging.openfi.re
  - www-beta.openfi.re
  - open-fire.appspot.com
  - www.openfi.re
  - openfi.re
  enabled_rewriters:
  - ProxyCss
  - ProxyImages
  - ProxyJs
  - ConvertMetaTags
  - InlineCss
  - InlineJs
  - InlineImages
  - InlinePreviewImages
  - CollapseWhitespace
  - CombineHeads
  - ElideAttributes
  - RemoveComments
  - MinifyCss
  - CombineCss
  - MoveCssToHead
  - WebpOptimization
  - ImageConvertToJpeg
  - ImageRecompressJpeg
  - ImageProgressiveJpeg
  - ImageRecompressPng
  - ImageStripMetadata
  - ImageStripColorProfile
  - ImageResize
  - LazyloadImages
  - ImageAddDimensions
  - CombineJs
  - JsOptimize
  disabled_rewriters:
  - LeftTrimUrls
  - DeferJs


#### ===== Custom Admin Pages
admin_console:
  pages:
  - name: L9 Dashboard
    url: /go/admin/dashboard
  - name: JIRA
    url: /go/admin/jira
  - name: Confluence
    url: /go/admin/wiki
  - name: Crowd (SSO)
    url: /go/admin/sso
  - name: Watchdog
    url: /go/admin/watchdog
  - name: AppStats
    url: /_ah/stats
  - name: AWS
    url: /go/admin/aws


#### ===== Error Handlers
error_handlers:
  - file: errors/default_error.html
  - error_code: over_quota
    file: errors/over_quota.html
  - error_code: dos_api_denial
    file: errors/dos_denial.html
  - error_code: timeout
    file: errors/timeout.html


#### ===== Site Handlers
handlers:


###### Library/system mappings

# AppTools: development + debugging console
- url: /_ah/apptools.*
  script: lib.apptools.gateway
  login: admin
  auth_fail_action: unauthorized

- url: /_app/manifest.*
  script: lib.apptools.gateway
  login: optional
  secure: optional
  auth_fail_action: unauthorized

- url: /_app/sitemap.*
  script: lib.apptools.gateway
  login: optional
  secure: optional
  auth_fail_action: unauthorized

# AppTrace: memory profiling
- url: /_ah/apptrace.*
  script: lib.dist.apptrace.overview.main
  login: admin
  auth_fail_action: unauthorized

# AppEngine Pipelines
- url: /_ah/pipeline.*
  script: main.pipelines

# Instance Warmup Hook
- url: /_ah/warmup.*
  script: main.warmup
  login: admin
  auth_fail_action: unauthorized

# Backend Start Hook
- url: /_ah/start.*
  script: main.backend
  login: admin
  auth_fail_action: unauthorized

# Embedded Admin Panel
- url: /_dev/console.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /_dev/console/.*
  script: google.appengine.ext.admin.application
  login: admin

###### Asset Handlers

# Images (Static)
- url: /assets/img/static
  static_dir: assets/img/static
  expiration: "1m"

# Style (Static)
- url: /assets/style/static
  static_dir: assets/style/static
  mime_type: text/css
  expiration: "1m"

# Scripts (Static)
- url: /assets/js/static
  static_dir: assets/js/static
  mime_type: text/javascript
  expiration: "1m"

# Generic (Static)
- url: /assets/ext/static
  static_dir: assets/ext/static
  expiration: "364d"

# Dynamic Assets
- url: /assets/.*
  script: main.DynamicAsset


###### Static Handlers

# Root-level files
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "0m"

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(.*)
  expiration: "0m"

# Static HTML5 Appcache Manifest
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/appcache/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0m"

# Chrome Extensions
- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: static/\1
  upload: static/(.*\.crx)


###### Static directory
- url: /static
  static_dir: static


###### Everything else goes to AppTools
- url: /.*
  login: optional
  secure: optional
  script: lib.apptools.dispatch.gateway
  auth_fail_action: redirect
